=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenAi::ChatCompletionRole
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenAi::ChatCompletionRole do
  let(:instance) { OpenAi::ChatCompletionRole.new }

  describe 'test an instance of ChatCompletionRole' do
    it 'should create an instance of ChatCompletionRole' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenAi::ChatCompletionRole)
    end
  end

end
