=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenAi::RealtimeServerEventRateLimitsUpdatedRateLimitsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenAi::RealtimeServerEventRateLimitsUpdatedRateLimitsInner do
  let(:instance) { OpenAi::RealtimeServerEventRateLimitsUpdatedRateLimitsInner.new }

  describe 'test an instance of RealtimeServerEventRateLimitsUpdatedRateLimitsInner' do
    it 'should create an instance of RealtimeServerEventRateLimitsUpdatedRateLimitsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenAi::RealtimeServerEventRateLimitsUpdatedRateLimitsInner)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "limit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "remaining"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reset_seconds"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
