=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenAi::RunStepDetailsToolCallsFileSearchRankingOptionsObject
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenAi::RunStepDetailsToolCallsFileSearchRankingOptionsObject do
  let(:instance) { OpenAi::RunStepDetailsToolCallsFileSearchRankingOptionsObject.new }

  describe 'test an instance of RunStepDetailsToolCallsFileSearchRankingOptionsObject' do
    it 'should create an instance of RunStepDetailsToolCallsFileSearchRankingOptionsObject' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenAi::RunStepDetailsToolCallsFileSearchRankingOptionsObject)
    end
  end

  describe 'test attribute "ranker"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["default_2024_08_21"])
      # validator.allowable_values.each do |value|
      #   expect { instance.ranker = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "score_threshold"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
