=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenAi::RunStepDeltaStepDetailsMessageCreationObjectMessageCreation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenAi::RunStepDeltaStepDetailsMessageCreationObjectMessageCreation do
  let(:instance) { OpenAi::RunStepDeltaStepDetailsMessageCreationObjectMessageCreation.new }

  describe 'test an instance of RunStepDeltaStepDetailsMessageCreationObjectMessageCreation' do
    it 'should create an instance of RunStepDeltaStepDetailsMessageCreationObjectMessageCreation' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenAi::RunStepDeltaStepDetailsMessageCreationObjectMessageCreation)
    end
  end

  describe 'test attribute "message_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
